### ISSUE TITLE
请不要移除 authlib-injector 代码中的 copyright notice

### ISSUE THREAD

**Issue by yushijinhun** [Tungstend/TouchInjector#1]
您好，我是 [authlib-injector](https://github.com/yushijinhun/authlib-injector) 项目的作者。我在此项目中发现您使用了 authlib-injector 的不少代码，对此我感到十分荣幸。authlib-injector 是使用 AGPLv3 协议的开源软件，其源文件中包含了 [copyright notice](https://github.com/yushijinhun/authlib-injector/blob/a132a2964ddd7f47aa48942acb7c21c092c2bc64/src/main/java/moe/yushi/authlibinjector/AuthlibInjector.java#L1-L16)，您不应该移除它们。

此外，由于您在本项目中使用了 authlib-injector 的代码，因此您的项目也应当使用 AGPLv3 协议。

希望您能够遵守 AGPLv3 协议，将删除的 copyright notice 恢复，并将此项目协议变为 AGPLv3。

**Comment by Tungstend** [comment]
好的，但是要稍等一会，我现在有些其他事，晚上或者明天处理

**Comment by Tungstend** [comment]
已经为所有照搬或者借鉴你的类添加了 copyright notice，协议也已经添加，我并不十分了解协议啥的，抱歉了，另外也是感谢你的项目为我提供了一些思路，改得有啥问题就 reopen 好了
